<definitions name = "getAllEvents"
   targetNamespace = "http://www.examples.com/wsdl/MyService.wsdl"
   xmlns = "http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap = "http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns = "http://www.examples.com/wsdl/MyService.wsdl"
   xmlns:xsd = "http://www.w3.org/2001/XMLSchema">

   <message name = "request">
      <part name = "request_data" type = "xsd:string"/>
   </message>

   <message name = "response">
      <part name = "response_data" type = "xsd:string"/>
   </message>
   
   <portType name = "getAllEvents_function">
      <operation name = "getAllEvents_event">
         <input message = "tns:request"/>
         <output message = "tns:response"/>
      </operation>
   </portType>

   <binding name = "getAllEvents_Binding" type = "tns:getAllEvents_function">
      <soap:binding style = "rpc" transport = "http://schemas.xmlsoap.org/soap/http"/>

      <operation name = "getAllEvents_event">
         <soap:operation soapAction = "getAllEvents_event"/>

         <input>
            <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/" namespace = "urn:examples:getAllEvents" use = "encoded"/>
         </input>
         <output>
            <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/" namespace = "urn:examples:getAllEvents" use = "encoded"/>
         </output>
      </operation>
      
   </binding>

   <service name = "getAllEvents">
      <documentation>WSDL File for MyService</documentation>
      <port binding = "tns:getAllEvents_Binding" name = "getAllEvents_function">
         <soap:address location = "http://localhost:8001/getAllEvents" />
      </port>
   </service>
</definitions>